### ISSUE TITLE
Prometheus metrics formatting error.

### ISSUE THREAD

**Issue by andrew-pickin-epi** [epimorphics/standard-reports-manager#11]
Metrics are of form:
```
jvm_memory_used_bytes{area="heap",id="PS Survivor Space",} 0.0
```
Final comma inside braces is invalid.

**Comment by andrew-pickin-epi** [comment]
https://github.com/prometheus/prometheus/issues/5196

**Comment by der** [comment]
Does appear to be similar to prometheus/prometheus#5196 so fix applied.

Note fix only applied in `master` not `dev` but deployment.yaml has been changed to deploy direct from master.

**Comment by andrew-pickin-epi** [comment]
Now scraping successfully
